plugins {
	id 'buildlogic.marlkit-common-conventions'
   	id 'org.gradlex.java-module-testing'
   	id 'jacoco'
}


application {
    mainClass = 'marlkit.test.GUITestAgent'
    mainModule = 'marlkit.base'
}


tasks.withType(JavaExec) {
    jvmArgs '--add-modules', 'ALL-MODULE-PATH'
}


javaModuleTesting.whitebox(testing.suites.getByName("test")){
	requires.add("org.testng")
	opensTo.add("org.testng")
	requires.add("org.assertj.core")
	requires.add("org.mockito")
}

dependencies {
	testImplementation 'org.mockito:mockito-core:5.15.2'
	api libs.madkit
    testImplementation libs.testng
    testImplementation libs.assertJ
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.19.1'
    //implementation 'org.encog:encog-core:3.3.0'
}

tasks.named('test') {
    useTestNG()
    maxParallelForks = "9"
    minHeapSize = "2048m"
    maxHeapSize = "4096m"

    testLogging {
        events "passed", "skipped", "failed"
        exceptionFormat "full"
        showStandardStreams = true
    }
}

jacocoTestReport {
    reports {
        xml.required = true
    }
}
test.finalizedBy jacocoTestReport
