stages:
  - build
  - test

variables:
  VERSION: "0.9"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

.gradle_script: &gradle_script
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME
  - mkdir -p $GRADLE_USER_HOME

default:
  tags:
    - linux
  image: eclipse-temurin:25-jdk-alpine-3.21
  before_script:
    - *gradle_script
  cache: &global_cache
    key: $CI_PROJECT_ID-$CI_COMMIT_REF_SLUG
    paths:
      - .gradle/caches     
      - .gradle/wrapper     
      - .gradle/notifications
      - build

build:
  stage: build
  script: ./gradlew --build-cache assemble

test:
  stage: test
  script: ./gradlew --build-cache check
  cache:
    # inherit all global cache settings
    <<: *global_cache
    # override the policy
    policy: pull
  artifacts:
    when: on_failure
    paths:
      - MARLKIT/build/reports/tests/test/*
