variables:
  VERSION: "1.0.0"

stages:
  - build
  - test

.gradle_script: &gradle_script
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME
  - mkdir -p $GRADLE_USER_HOME

default:
  tags:
    - linux
  image: eclipse-temurin:23.0.1_11-jdk-alpine
  before_script:
    - *gradle_script
  cache: &global_cache
    key: MARLKIT-$CI_PROJECT_ID
    paths:
      - MARLKIT/build
      - gradle/wrapper/
      - .gradle

build:
  stage: build
  script: ./gradlew --build-cache assemble

test:
  stage: test
  script: ./gradlew --build-cache check
  artifacts:
    when: on_failure
    reports:
      junit: MARLKIT/build/test-results/test/**/TEST-*.xml
