plugins {
	id 'buildlogic.marlkit-common-conventions'
}

dependencies {
	api project(':MARLKIT')
	api project(':MARL-Methods')
	implementation libs.classgraph
	implementation libs.commonmark
	implementation libs.commonmarkTables
	testImplementation 'org.mockito:mockito-core:5.24.0'
    testImplementation libs.testng
    testImplementation libs.assertJ
}

javafx {
	modules = ['javafx.base', 'javafx.controls', 'javafx.graphics', 'javafx.web']
	configuration = 'api'
}

tasks.named('test') {
    useTestNG()
}

tasks.named('processResources') {
	from('src/main/java') {
		include '**/README.md'
	}
	filesMatching('marlkit/collectingresource/README.md') {
		filter { line ->
			line.replace('../../../resources/marlkit/collectingresource/figures/', 'figures/')
		}
	}
	filesMatching('marlkit/foraging/README.md') {
		filter { line ->
			line.replace('../../../resources/marlkit/foraging/figures/', 'figures/')
		}
	}
	filesMatching('marlkit/gooryield/README.md') {
		filter { line ->
			line.replace('../../../resources/marlkit/gooryield/figures/', 'figures/')
		}
	}
	filesMatching('marlkit/preyhunter/README.md') {
		filter { line ->
			line.replace('../../../resources/marlkit/preyhunter/figures/', 'figures/')
		}
	}
}

application {
	mainClass = 'marlkit.launcher.ExperimentLauncherMenu'
	mainModule = 'marlkit.xp'
}


tasks.withType(JavaExec) {
    jvmArgs '--add-modules', 'ALL-MODULE-PATH'
}
