plugins {
	id 'buildlogic.marlkit-common-conventions'
}

tasks.withType(JavaExec) {
    jvmArgs '--add-modules', 'ALL-MODULE-PATH'
}

dependencies {
	api project(':MARLKIT')
	testImplementation 'org.mockito:mockito-core:5.15.2'
    testImplementation libs.testng
    testImplementation libs.assertJ
}

tasks.named('test') {
    useTestNG()
}

